# Generated by Django 5.0.6 on 2024-06-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='Email', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='fname',
            field=models.CharField(default='First Name', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='lname',
            field=models.CharField(default='Last Name', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='USERNAME', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='Password', max_length=50),
        ),
    ]
