# Generated by Django 5.0.6 on 2024-06-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_users_name_users_email_users_fname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='Email', max_length=100)),
                ('password', models.CharField(default='Password', max_length=50)),
                ('isLoggedIn', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
