# Generated by Django 5.0.6 on 2024-06-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_register_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='message',
            field=models.CharField(default='200 OK', max_length=10),
        ),
        migrations.AddField(
            model_name='login',
            name='status',
            field=models.CharField(default='success', max_length=10),
        ),
    ]
