# Generated by Django 5.0.6 on 2024-06-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_user_delete_login_delete_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
