# Generated by Django 5.0.6 on 2024-06-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='message',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(default='200 OK', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='success', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='Success', max_length=10),
        ),
    ]
