# Generated by Django 5.0.6 on 2024-06-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_message_user_fname_user_lname_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileImage',
            field=models.CharField(default='', max_length=50),
        ),
    ]
